### ISSUE TITLE
User Story: Add a place.

### ISSUE THREAD

**Issue by GreenNinjaBoy** [GreenNinjaBoy/Scottish-Gems-PP4#11]
As a user I am able to add a place by inputting information to share my recommendation to other users.

# Acceptance Criteria

- Form where the user can add place information and photos.
- User can choose withier to save or cancel their recommendation.

# Tasks

- [ ] Create an "add-gem" form.
- [ ] Create an "add-gem" view. 
- [ ] Create a place model.
