### ISSUE TITLE
User Story: Testing Code.

### ISSUE THREAD

**Issue by GreenNinjaBoy** [GreenNinjaBoy/Scottish-Gems-PP4#14]
As a developer I can create a suite of tests, to easily be able to find out if site updates create issues in the codebase.

# Acceptance criteria
- Django unit tests with 90%+ coverage

# Tasks
- [ ] Create test_forms
- [ ] Create test_models
- [ ] Create test_views
- [ ] Install 'coverage' and generate report
