### ISSUE TITLE
User Story: Deployment

### ISSUE THREAD

**Issue by GreenNinjaBoy** [GreenNinjaBoy/Scottish-Gems-PP4#3]
As a developer I can deploy the website to that it becomes accessible to users.

# Acceptance Criteria
- Functionality deployment to Heroku

# Tasks 
- [ ] Setup Django project & app
- [ ] Link PostgreSQL via Elephant SQL
- [ ] Link Cloudinary (for assets and static files)
- [ ] Create Config Vars in Heroku
- [ ] Hide SECRET_KEY in env.py
- [ ] Add domain to ALLOWED_HOSTS
- [ ] Install gunicorn
- [ ] Create Procfile
