### ISSUE TITLE
User Story: Create Comment

### ISSUE THREAD

**Issue by GreenNinjaBoy** [GreenNinjaBoy/Scottish-Gems-PP4#7]
As a user I can leave a comment on a place, to share my experience with other users.

# Acceptance criteria 

- Once signed in a user can leave a comment on a place.
- User receives feedback message.
- Comment form is in the detail view.

# Tasks

- [ ] Create comment model.
- [ ] Create comment form.
- [ ] Update place_detail to include comment form.
